Solicitud de JosuesMolina para la legión
josuesfakee/legion-del-mal-master pull request #1
Opened 2023-01-27 07:06 UTC by JosuesMolina

##Modificaciones

###Aplicando a la legión del mal

2023-01-27 07:09 UTC, josuesfakee requested changes
Favor de agregar sus poderes

2023-01-27 07:09 UTC, josuesfakee commented on aspirantes/Josue.md
> +Quiero aplicar a la legion del mal
Hace falta describir sus poderes

2023-01-27 07:15 UTC, JosuesMolina commented on aspirantes/Josue.md
> +Quiero aplicar a la legion del mal
Entendido. Agrego mis poderes

2023-01-27 23:49 UTC, josuesfakee approved these changes

2023-01-28 00:00 UTC, josuesfakee commented
- Solicitud aceptada

2023-01-28 00:01 UTC, merged